providers:
- name: testprovider
  type: openai
  module: src.providers.openai
  class: OpenAIProvider
  api_key_env: OPENAI_API_KEY
  base_url: https://api.openai.com/v1
  models:
  - gpt-4
  priority: 10
  enabled: true
