providers:
  - name: "openai"
    type: "openai"
    api_key_env: "OPENAI_API_KEY"
    base_url: "https://api.openai.com/v1"
    models:
      - "gpt-4"
      - "gpt-3.5-turbo"
      - "text-davinci-003"
      - "text-embedding-ada-002"
    enabled: true
    priority: 1
    timeout: 30
    rate_limit: 1000
    retry_attempts: 3
    retry_delay: 1.0
    headers:
      "Authorization": "Bearer ${OPENAI_API_KEY}"

  - name: "anthropic"
    type: "anthropic"
    api_key_env: "ANTHROPIC_API_KEY"
    base_url: "https://api.anthropic.com"
    models:
      - "claude-3-sonnet-20240229"
      - "claude-3-opus-20240229"
    enabled: true
    priority: 2
    timeout: 30
    rate_limit: 1000
    retry_attempts: 3
    retry_delay: 1.0
    headers:
      "x-api-key": "${ANTHROPIC_API_KEY}"
      "anthropic-version": "2023-06-01"
